name: main
on: [push]
jobs:
  run-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Install pylint
        run: pip3 install pylint
      - name: Run linter
        run: pylint $(git ls-files '*.py')
